[package]
name = "ast"
version = "0.0.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
serde = { version = "1.0.136", features = ["derive"] }

[dev-dependencies]
insta = { version = "1.12.0", features = ["glob"] }
