[package]
name = "ast"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }

common = { path = "../common" }
symbol_table = { path = "../symbol_table" }
