[package]
name = "lightc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
tempfile = "3.3.0"

codegen = { path = "../codegen" }
common = { path = "../common" }
hir = { path = "../hir" }
lexer = { path = "../lexer" }
parser = { path = "../parser" }
symbol_table = { path = "../symbol_table" }
type_checker = { path = "../type_checker" }
